{
  "name": "coalink",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "export NODE_ENV=production && webpack --progress --profile --colors -d --devtool inline-source-map",
    "apidoc": "apidoc -i coalink/ -o docs/api/",
    "test": "py.test || true",
    "fulltest": "py.test --cov-report term-missing -n4 --cov coalink || true",
    "dev": "webpack-dev-server --progress --colors -d --devtool inline-source-map",
    "devserver": "export FLASK_CONFIG=development && python manage.py runserver",
    "renew-db": "export FLASK_CONFIG=development && rm -rf migrations/ && dropdb coalink_dev_db && createdb coalink_dev_db -U coalink && python manage.py db init && python manage.py db migrate && python manage.py db upgrade && python manage.py initialize",
    "remote-dev": "webpack-dev-server --config ./webpack.remote.config.js --progress --colors -d --devtool inline-source-map",
    "deploy": "export NODE_ENV=production && webpack -p --progress --colors"
  },
  "repository": {
    "type": "git",
    "url": "git@git.coding.net:coalink/coalink.git"
  },
  "apidoc": {
    "title": "Rest Api接口文档"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^5.8.12",
    "babel-loader": "^5.3.2",
    "clean-webpack-plugin": "^0.1.3",
    "css-loader": "^0.15.6",
    "extract-text-webpack-plugin": "^0.8.2",
    "file-loader": "^0.8.4",
    "html-loader": "^0.3.0",
    "less": "^2.5.1",
    "less-loader": "^2.2.0",
    "lodash": "^3.10.1",
    "minimatch": "^2.0.10",
    "node-libs-browser": "^0.5.2",
    "node-sass": "^3.2.0",
    "react-hot-loader": "^1.2.8",
    "sass-loader": "^2.0.0",
    "style-loader": "^0.12.3",
    "url-loader": "^0.5.6",
    "webpack": "^1.10.5",
    "webpack-dev-server": "^1.10.1",
    "webpack-md5-hash": "0.0.4"
  },
  "dependencies": {
    "alt": "^0.17.7",
    "bootstrap": "^3.3.5",
    "classnames": "^2.1.3",
    "es5-shim": "^4.2.0",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.9",
    "font-awesome": "^4.4.0",
    "history": "^1.13.0",
    "html5shiv": "^3.7.3",
    "immutable": "^3.7.4",
    "joi": "^6.9.1",
    "jquery": "^2.1.4",
    "numeral": "^1.5.3",
    "object-assign": "^4.0.1",
    "react": "^0.14.1",
    "react-addons-create-fragment": "^0.14.1",
    "react-addons-linked-state-mixin": "^0.14.1",
    "react-addons-perf": "^0.14.1",
    "react-addons-pure-render-mixin": "^0.14.1",
    "react-addons-transition-group": "^0.14.1",
    "react-addons-update": "^0.14.1",
    "react-dom": "^0.14.1",
    "react-draggable2": "^0.6.0",
    "react-highcharts": "^5.0.0",
    "react-mixin": "^3.0.1",
    "react-router": "^1.0.0-rc3",
    "react-tap-event-plugin": "^0.2.1",
    "react-timer-mixin": "^0.13.3",
    "react-validation-mixin": "^4.2.0",
    "simditor": "^2.2.3",
    "store": "^1.3.17",
    "underscore": "^1.8.3"
  }
}
